<a href="https://colab.research.google.com/github/Roghiehghahremani/Deep-Learning-With-PyTorch---Full-Course_Patrick-Loeber/blob/main/02_tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

# Everything in pytorch is based on Tensor operations.
# A tensor can have different dimensions
# so it can be 1d, 2d, or even 3d and higher

# scalar, vector, matrix, tensor

# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(x)

x = torch.empty(3) # vector, 1D
print(x)

x = torch.empty(2,3) # matrix, 2D
print(x)

x = torch.empty(2,2,3) # tensor, 3 dimensions
#x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

tensor([0.])
tensor([-2.2305e-37,  4.4736e-41, -2.2305e-37])
tensor([[ 1.6905e-34,  0.0000e+00, -2.2305e-37],
        [ 4.4736e-41,  8.9683e-44,  0.0000e+00]])
tensor([[[1.8899e-34, 0.0000e+00, 0.0000e+00],
         [2.3510e-38, 1.3500e-37, 0.0000e+00]],

        [[1.0842e-19, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])
tensor([[0.2854, 0.3616, 0.6162],
        [0.4577, 0.3565, 0.7534],
        [0.1146, 0.7010, 0.8851],
        [0.6500, 0.3507, 0.6226],
        [0.2699, 0.3456, 0.9516]])


In [4]:
# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
print(x)

# check size
print(x.size())

# check data type
print(x.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([5, 3])
torch.float32


In [5]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

# check type
print(x.dtype)

# construct from data
x = torch.tensor([5.5, 3])
print(x.size())
print(x.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16
torch.Size([2])
torch.float32


In [6]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)

tensor([5.5000, 3.0000], requires_grad=True)


In [7]:
# Operations
y = torch.rand(2, 2)
x = torch.rand(2, 2)

# elementwise addition
z = x + y
# torch.add(x,y)

# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
# y.add_(x)

# substraction
z = x - y
z = torch.sub(x, y)

# multiplication
z = x * y
z = torch.mul(x,y)

# division
z = x / y
z = torch.div(x,y)



In [8]:
# Slicing
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

# Get the actual value if only 1 element in your tensor
print(f'{x[1,1].item():.3f}')

tensor([[0.7600, 0.4023, 0.9053],
        [0.0694, 0.3185, 0.7521],
        [0.0111, 0.7881, 0.7610],
        [0.4809, 0.7753, 0.3437],
        [0.4338, 0.1458, 0.0801]])
tensor([0.7600, 0.0694, 0.0111, 0.4809, 0.4338])
tensor([0.0694, 0.3185, 0.7521])
tensor(0.3185)
0.318


In [9]:
# Reshape with torch.view()
x = torch.randn(4, 4)
print(x)
y = x.view(16)
print(y)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(z)
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())



tensor([[ 2.3715, -0.9183, -1.4066, -0.7870],
        [-0.0691, -1.0372, -0.4761,  0.9875],
        [-0.5361, -0.1050, -1.4711,  0.6948],
        [ 1.0669,  0.5513,  0.3385, -0.5003]])
tensor([ 2.3715, -0.9183, -1.4066, -0.7870, -0.0691, -1.0372, -0.4761,  0.9875,
        -0.5361, -0.1050, -1.4711,  0.6948,  1.0669,  0.5513,  0.3385, -0.5003])
tensor([[ 2.3715, -0.9183, -1.4066, -0.7870, -0.0691, -1.0372, -0.4761,  0.9875],
        [-0.5361, -0.1050, -1.4711,  0.6948,  1.0669,  0.5513,  0.3385, -0.5003]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [10]:
# Numpy
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
a = torch.ones(5)
print(a)
print(a.dtype)
# torch to numpy with .numpy()
b = a.numpy()
print(b)
print(type(b))
print()
# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
torch.float32
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [11]:
# numpy to torch with .from_numpy(x)
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)
print()
# again be careful when modifying
a += 1
print(a)
print(b)



[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [20]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    print(device)
    print(x)
    print()
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    print(y)
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    print(x)
    z = x + y
    print(z)
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")       # ``.to`` can also change dtype together!
    print(z)
    # z = z.numpy()


cuda
tensor([[ 2.3715, -0.9183, -1.4066, -0.7870],
        [-0.0691, -1.0372, -0.4761,  0.9875],
        [-0.5361, -0.1050, -1.4711,  0.6948],
        [ 1.0669,  0.5513,  0.3385, -0.5003]], device='cuda:0')

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
tensor([[ 2.3715, -0.9183, -1.4066, -0.7870],
        [-0.0691, -1.0372, -0.4761,  0.9875],
        [-0.5361, -0.1050, -1.4711,  0.6948],
        [ 1.0669,  0.5513,  0.3385, -0.5003]], device='cuda:0')
tensor([[ 3.3715,  0.0817, -0.4066,  0.2130],
        [ 0.9309, -0.0372,  0.5239,  1.9875],
        [ 0.4639,  0.8950, -0.4711,  1.6948],
        [ 2.0669,  1.5513,  1.3385,  0.4997]], device='cuda:0')
tensor([[ 3.3715,  0.0817, -0.4066,  0.2130],
        [ 0.9309, -0.0372,  0.5239,  1.9875],
        [ 0.4639,  0.8950, -0.4711,  1.6948],
        [ 2.0669,  1.5513,  1.3385,  0.4997]], device='cuda:0')
