<a href="https://colab.research.google.com/github/Roghiehghahremani/Deep-Learning-With-PyTorch---Full-Course_Patrick-Loeber/blob/main/17_Save_Load_Models_CPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn

In [5]:
# Load the Drive helper and mount
from google.colab import drive
drive.mount('/content/drive/')
%cd /content/drive/MyDrive/DLPyTorch_Patrick_Loeber/Save_Load

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).
/content/drive/MyDrive/DLPyTorch_Patrick_Loeber/Save_Load


In [18]:
class Model(nn.Module):
  def __init__(self,n_input_features):
    super(Model,self).__init__()
    self.linear = nn.Linear(n_input_features,1)

  def forward(self,x):
    y_pred = torch.Sigmoid(self.linear(x))
    return y_pred
model = Model(n_input_features=6)
for param in model.parameters():
  print(param)
print()
# train your model

FILE = "model.pth" # pth stands for pytorch
torch.save(model,FILE)
model = torch.load(FILE)

model.eval()

for param in model.parameters():
  print(param)

Parameter containing:
tensor([[-0.2378,  0.3511, -0.2029,  0.2321, -0.2253,  0.1295]],
       requires_grad=True)
Parameter containing:
tensor([0.2992], requires_grad=True)

Parameter containing:
tensor([[-0.2378,  0.3511, -0.2029,  0.2321, -0.2253,  0.1295]],
       requires_grad=True)
Parameter containing:
tensor([0.2992], requires_grad=True)


<ipython-input-18-0551424631ea>:17: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model = torch.load(FILE)


In [14]:
class Model(nn.Module):
  def __init__(self,n_input_features):
    super(Model,self).__init__()
    self.linear = nn.Linear(n_input_features,1)

  def forward(self,x):
    y_pred = torch.Sigmoid(self.linear(x))
    return y_pred
model = Model(n_input_features=6)

for param in model.parameters():
  print(param)
print()
# train your model

# option 2:


####### State DICT ########
FILE = "model.pth" # pth stands for pytorch
torch.save(model.state_dict(),FILE)


loaded_model = Model(n_input_features=6)
loaded_model.load_state_dict(torch.load(FILE))
loaded_model.eval()

for param in loaded_model.parameters():
  print(param)

Parameter containing:
tensor([[ 0.0768,  0.0079, -0.3019, -0.3034, -0.0330,  0.1155]],
       requires_grad=True)
Parameter containing:
tensor([0.0235], requires_grad=True)

Parameter containing:
tensor([[ 0.0768,  0.0079, -0.3019, -0.3034, -0.0330,  0.1155]],
       requires_grad=True)
Parameter containing:
tensor([0.0235], requires_grad=True)


<ipython-input-14-f47d66dc3dde>:25: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loaded_model.load_state_dict(torch.load(FILE))


In [34]:
class Model(nn.Module):
  def __init__(self,n_input_features):
    super(Model,self).__init__()
    self.linear = nn.Linear(n_input_features,1)

  def forward(self,x):
    y_pred = torch.Sigmoid(self.linear(x))
    return y_pred
model = Model(n_input_features=6)

# train your model
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)
#print(optimizer.state_dict())

checkpoint = {
    "epoch": 90,
    "model_state":model.state_dict(),
    "optim_state":optimizer.state_dict()
}

print('checkpoint',checkpoint)
print()
torch.save(checkpoint,"checkpoint.pth")

#loaded_checkpoint = Model(n_input_features=6)
loaded_checkpoint = torch.load("checkpoint.pth")
loaded_epoch = loaded_checkpoint["epoch"]
print(loaded_epoch)

loaded_model = Model(n_input_features=6)
loaded_model.load_state_dict(checkpoint['model_state'])
print('loaded_model', loaded_model)

loaded_optimizer = torch.optim.SGD(loaded_model.parameters(), lr = 0)
loaded_optimizer.load_state_dict(loaded_checkpoint["optim_state"])
print(loaded_optimizer.state_dict())

checkpoint {'epoch': 90, 'model_state': OrderedDict([('linear.weight', tensor([[-0.2098, -0.2088,  0.3807,  0.1653, -0.2415,  0.0568]])), ('linear.bias', tensor([0.0833]))]), 'optim_state': {'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'fused': None, 'params': [0, 1]}]}}

90
loaded_model Model(
  (linear): Linear(in_features=6, out_features=1, bias=True)
)
{'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'fused': None, 'params': [0, 1]}]}


<ipython-input-34-2acbcd38b81c>:27: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loaded_checkpoint = torch.load("checkpoint.pth")
